#include "user_actions.h"
#include "logic.h"

#include <stdio.h>

#define ENTER_ASCII_VALUE 13
#define SMALLEST_UPPER_CASE_ASCII_VALUE 65
#define HIGHEST_UPPER_CASE_ASCII_VALUE 90
#define SMALLEST_LOWER_CASE_ASCII_VALUE 97
#define HIGHEST_LOWER_CASE_ASCII_VALUE 122

const char *HANGMAN_ASCII_ART[] = {
    " ",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM          MMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       M   MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMM            MMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM   M       M   MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMM            MMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM   M       M   MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMM            MMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM   M       M   MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM    M    MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMM   MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMM   MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMM   MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMM   MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"};

const char *game_over_ascii_art[] =
    {
        "\n\r"
        "   ____                         ___                 \n\r"
        "  / ___| __ _ _ __ ___   ___   / _ \\__   _____ _ __ \n\r"
        " | |  _ / _` | '_ ` _ \\ / _ \\ | | | \\ \\ / / _ | '__|\n\r"
        " | |_| | (_| | | | | | |  __/ | |_| |\\ V |  __| |   \n\r"
        "  \\____|\\__,_|_| |_| |_|\\___|  \\___/  \\_/ \\___|_|   \n\r"
        "\n\r"};

const char *win_ascii_art[] =
    {
        "\n\r"
        " __   __                       _         _  \n\r"
        " \\ \\ /___  _   _    __      _(_)_ __   | | \n\r"
        "  \\ V / _ \\| | | |   \\ \\ /\\ / | | '_ \\  | | \n\r"
        "   | | (_) | |_| |    \\ V  V /| | | | | |_| \n\r"
        "   |_|\\___/ \\__,_|     \\_/\\_/ |_|_| |_| (_) \n\r"
        "\n\r"};

const char *starting_screen[] =
    {
        "\n\r"
        "  _   _                   __  __              \n\r"
        " | | | | __ _ _ __   __ _|  \\/  | __ _ _ __   \n\r"
        " | |_| |/ _` | '_ \\ / _` | |\\/| |/ _` | '_ \\  \n\r"
        " |  _  | (_| | | | | (_| | |  | | (_| | | | | \n\r"
        " |_| |_|\\__,_|_| |_|\\__, |_|  |_|\\__,_|_| |_| \n\r"
        "                    |___/ Terminal Edition    \n\r"
        "\n\r"};

const char *stats[] =
    {
        "____________________________________________________\n\r"
        "STATS\n\r"
        "____________________________________________________"
        "\n\r"
        "NO. OF TRIES: ",
        "placeholder\n\r",
        "\n\rNO. OF MISENTRIES: ",
        "placeholder\n\r",
        "____________________________________________________\n\r"
        "\n\r"};

/**
 * @brief drwas hangman at the given position to the console
 * 
 * @param incorrect 
 */
void draw_hangman(int incorrect)
{
    print_word(HANGMAN_ASCII_ART[incorrect]);
}

/**
 * @brief fills the stats array with the given array at the given position
 * @details position = 1 => over all tries; position = 3 => misentries, function checks if position has one of these two values
 * @param array_with_number 
 * @param position 
 */
void fill_stats(const char *array_with_number, int position)
{
    if (position == 1 || position == 3)
    {
        stats[position] = array_with_number;
    }
}

/**
 * @brief draws game over ascci art to the console
 */
void draw_game_over()
{
    print_word(game_over_ascii_art[0]);
}

/**
 * @brief draws statistics to the console
 */
void draw_stats()
{
    for (int i = 0; i < sizeof(stats); i++)
    {
        print_word(stats[i]);
    }
}

/**
 * @brief draws you win ascci art to the console
 */
void draw_you_win()
{
    print_word(win_ascii_art[0]);
}

/**
 * @brief draws starting screen ascci art to the console
 */
void draw_starting_scrren()
{
    print_word(starting_screen[0]);
}


/**
 * @brief Get the word to guess 
 * @details this function returns the size of the word, because the array is initialized empty with a fixed size, so the sizeof function would return always the same value for this array
 * @param word_to_guess array which gets filled by this function
 * @return int length of the given word
 */
int get_word_to_guess(char *word_to_guess)
{
    int position = 0;
    while (1)
    {
        print_word("\n\rEnter the word that should be guessed by your friends");
        char input = read();
        int input_ascii_value = input;
        if (input_ascii_value >= SMALLEST_UPPER_CASE_ASCII_VALUE && input_ascii_value <= HIGHEST_UPPER_CASE_ASCII_VALUE)
        {
            word_to_guess[position] = input;
        }
        else if (input_ascii_value >= SMALLEST_LOWER_CASE_ASCII_VALUE && input_ascii_value <= HIGHEST_LOWER_CASE_ASCII_VALUE)
        {
            word_to_guess[position] = toUpper(input);
        }
        else if (input_ascii_value  == ENTER_ASCII_VALUE)
        {
            return position;
        }
        position += 1;
    }
}

/**
 * @brief clears the console
 * 
 */
void clear_screen()
{
    print_word("\033[H\033[J");
}


/**
 * @brief prints single charcter to console by using printChar function
 * 
 * @param text 
 */
void print_single_character(char text)
{
    printChar(text);
}

/**
 * @brief reads input from console and returns it
 * 
 * @return char 
 */
char read()
{
    char input = read_input();
    return input;
}

/**
 * @brief prints 'String' to the console by using the printString function 
 * 
 * @param text 
 */
void print_word(const char *text)
{
    printString(text);
}
