#include "user_actions.h"
#include "logic.h"

#include <stdio.h>

const char *HANGMAN_ASCII_ART[] = {
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM          MMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       M   MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMM            MMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM   M       M   MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMM            MMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM   M       M   MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r",
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                              MMMMMMMMMMM\n\r"
    "MMM    MMMMM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    MMM   MMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM    M   MMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMM\n\r"
    "MMM       MMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM     MMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMM      MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMM            MMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM   M       M   MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMM  MM       MM  MMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMM       MMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM    M    MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMM   MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMM   MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMM   MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMM   MMM   MMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"
    "MMM                                      MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMM\n\r"
    "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\r"};

const char *game_over_ascii_art[] =
    {
        "\n\r"
        "   ____                         ___                 \n\r"
        "  / ___| __ _ _ __ ___   ___   / _ \\__   _____ _ __ \n\r"
        " | |  _ / _` | '_ ` _ \\ / _ \\ | | | \\ \\ / / _ | '__|\n\r"
        " | |_| | (_| | | | | | |  __/ | |_| |\\ V |  __| |   \n\r"
        "  \\____|\\__,_|_| |_| |_|\\___|  \\___/  \\_/ \\___|_|   \n\r"
        "\n\r"};

const char *win_ascii_art[] =
    {
        "\n\r"
        " __   __                       _         _  \n\r"
        " \\ \\ / ___  _   _    __      _(_)_ __   | | \n\r"
        "  \\ V / _ \\| | | |   \\ \\ /\\ / | | '_ \\  | | \n\r"
        "   | | (_) | |_| |    \\ V  V /| | | | | |_| \n\r"
        "   |_|\\___/ \\__,_|     \\_/\\_/ |_|_| |_| (_) \n\r"
        "\n\r"};

const char *starting_screen[] =
    {
        "\n\r"
        "  _   _                   __  __              \n\r"
        " | | | | __ _ _ __   __ _|  \\/  | __ _ _ __   \n\r"
        " | |_| |/ _` | '_ \\ / _` | |\\/| |/ _` | '_ \\  \n\r"
        " |  _  | (_| | | | | (_| | |  | | (_| | | | | \n\r"
        " |_| |_|\\__,_|_| |_|\\__, |_|  |_|\\__,_|_| |_| \n\r"
        "                    |___/ Terminal Edition    \n\r"
        "\n\r"};

const char *stats[] =
    {
        "____________________________________________________\n\r"
        "STATS\n\r"
        "____________________________________________________"
        "\n\r"
        "NO. OF TRIES: ",
        "placeholder\n\r",
        "\n\rNO. OF MISENTRIES: ",
        "placeholder\n\r",
        "____________________________________________________\n\r"
        "\n\r"};

/// @brief draws hangman picture
/// @param incorrect
void draw_hangman(int incorrect)
{
    print_guessed_word(HANGMAN_ASCII_ART[incorrect]);
}

void fill_tries_array(const char *number_as_character)
{

    stats[1] = number_as_character;
}
void fill_wrong_tries_array(const char *wrong_tries)
{
    stats[3] = wrong_tries;
}

void draw_game_over(void)
{
    print_guessed_word(game_over_ascii_art[0]);
}

void draw_stats(void)
{
    for (int i = 0; i < sizeof(stats); i++)
    {
        print_guessed_word(stats[i]);
    }
}

void draw_you_win(void)
{
    print_guessed_word(win_ascii_art[0]);
}

void draw_starting_scrren(void)
{
    print_guessed_word(starting_screen[0]);
}

int get_word_to_guess(char *word_to_guess)
{
    int position = 0;
    while (1)
    {
        print_guessed_word("\n\rEnter the word that should be guessed by your friends");
        char input = read();
        int input_ascii_value = input;
        if (input_ascii_value >= 65 && input_ascii_value <= 90)
        {
            word_to_guess[position] = input;
        }
        else if (input_ascii_value >= 97 && input_ascii_value <= 122)
        {
            word_to_guess[position] = toUpper(input);
        }
        else if (input_ascii_value == 13)
        {
            return position;
        }
        position += 1;
    }
}

void print_single_character(char text)
{
    printChar(text);
}

char read(void)
{
    char input = read_input();
    return input;
}

void print_guessed_word(const char *text)
{
    printString(text);
}

void print_word_to_guess(const char *text, int length)
{
    for(int i = 0; i< length-1; i++)
    {
        print_single_character(text[i]);
    }
}